//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathSymbolConverter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>calpha\tΑ</string>\r\n  <string>alpha\tα</string>\r\n  <string>cbeta\tΒ</string>\r" +
            "\n  <string>beta\tβ</string>\r\n  <string>cgamma\tΓ</string>\r\n  <string>gamma\tγ</stri" +
            "ng>\r\n  <string>cdelta\tΔ</string>\r\n  <string>delta\tδ</string>\r\n  <string>cepsilon" +
            "\tΕ</string>\r\n  <string>epsilon\tε</string>\r\n  <string>czeta\tΖ</string>\r\n  <string" +
            ">zeta\tζ</string>\r\n  <string>ceta\tΗ</string>\r\n  <string>eta\tη</string>\r\n  <string" +
            ">ctheta\tΘ</string>\r\n  <string>theta\tθ</string>\r\n  <string>ciota\tΙ</string>\r\n  <s" +
            "tring>iota\tι</string>\r\n  <string>ckappa\tΚ</string>\r\n  <string>kappa\tκ</string>\r\n" +
            "  <string>clambda\tΛ</string>\r\n  <string>lambda\tλ</string>\r\n  <string>cmu\tΜ</stri" +
            "ng>\r\n  <string>mu\tμ</string>\r\n  <string>cnu\tΝ</string>\r\n  <string>nu\tν</string>\r" +
            "\n  <string>cxi\tΞ</string>\r\n  <string>xi\tξ</string>\r\n  <string>comicron\tΟ</string" +
            ">\r\n  <string>omicron\tο</string>\r\n  <string>cpi\tΠ</string>\r\n  <string>pi\tπ</strin" +
            "g>\r\n  <string>crho\tΡ</string>\r\n  <string>rho\tρ</string>\r\n  <string>csigma\tΣ</str" +
            "ing>\r\n  <string>sigma\tσ</string>\r\n  <string>varsigma\tς</string>\r\n  <string>ctau\t" +
            "Τ</string>\r\n  <string>tau\tτ</string>\r\n  <string>cupsilon\tΥ</string>\r\n  <string>u" +
            "psilon\tυ</string>\r\n  <string>cphi\tΦ</string>\r\n  <string>phi\tφ</string>\r\n  <strin" +
            "g>cchi\tΧ</string>\r\n  <string>chi\tχ</string>\r\n  <string>cpsi\tΨ</string>\r\n  <strin" +
            "g>psi\tψ</string>\r\n  <string>comega\tΩ</string>\r\n  <string>omega\tω</string>\r\n  <st" +
            "ring>supone\t¹</string>\r\n  <string>suptwo\t²</string>\r\n  <string>supthree\t³</strin" +
            "g>\r\n  <string>supfour\t⁴</string>\r\n  <string>supfive\t⁵</string>\r\n  <string>supsix" +
            "\t⁶</string>\r\n  <string>supseven\t⁷</string>\r\n  <string>supeight\t⁸</string>\r\n  <st" +
            "ring>supnine\t⁹</string>\r\n  <string>supzero\t⁰</string>\r\n  <string>subone\t₁</strin" +
            "g>\r\n  <string>subtwo\t₂</string>\r\n  <string>subthree\t₃</string>\r\n  <string>subfou" +
            "r\t₄</string>\r\n  <string>subfive\t₅</string>\r\n  <string>subsix\t₆</string>\r\n  <stri" +
            "ng>subseven\t₇</string>\r\n  <string>subeight\t₈</string>\r\n  <string>subnine\t₉</stri" +
            "ng>\r\n  <string>subzero\t₀</string>\r\n  <string>supplus\t⁺</string>\r\n  <string>supmi" +
            "nus\t⁻</string>\r\n  <string>supequal\t⁼</string>\r\n  <string>supparentl\t⁽</string>\r\n" +
            "  <string>supparentr\t⁾</string>\r\n  <string>subplus\t₊</string>\r\n  <string>subminu" +
            "s\t₋</string>\r\n  <string>subequal\t₌</string>\r\n  <string>subparentl\t₍</string>\r\n  " +
            "<string>subparentr\t₎</string>\r\n  <string>int\t∫</string>\r\n  <string>iint\t∬</strin" +
            "g>\r\n  <string>iiint\t∭</string>\r\n  <string>oint\t∮</string>\r\n  <string>oiint\t∯</st" +
            "ring>\r\n  <string>oiiint\t∰</string>\r\n  <string>partial\t∂</string>\r\n  <string>pm\t±" +
            "</string>\r\n  <string>mp\t∓</string>\r\n  <string>times\t×</string>\r\n  <string>div\t÷<" +
            "/string>\r\n  <string>neq\t≠</string>\r\n  <string>le\t≤</string>\r\n  <string>ge\t≥</str" +
            "ing>\r\n  <string>ll\t≪</string>\r\n  <string>gg\t≫</string>\r\n  <string>approx\t≈</stri" +
            "ng>\r\n  <string>cong\t≅</string>\r\n  <string>infin\t∞</string>\r\n  <string>therefore\t" +
            "∴</string>\r\n  <string>because\t∵</string>\r\n  <string>in\t∈</string>\r\n  <string>not" +
            "in\t∉</string>\r\n  <string>ni\t∋</string>\r\n  <string>subset\t⊂</string>\r\n  <string>s" +
            "upset\t⊃</string>\r\n  <string>subseteq\t⊆</string>\r\n  <string>supseteq\t⊇</string>\r\n" +
            "  <string>cup\t∪</string>\r\n  <string>cap\t∩</string>\r\n  <string>emptyset\tø</string" +
            ">\r\n  <string>permil\t‰</string>\r\n  <string>top\t⊤</string>\r\n  <string>perp\t⊥</stri" +
            "ng>\r\n  <string>vdash\t⊢</string>\r\n  <string>models\t⊨</string>\r\n  <string>triangle" +
            "\t△</string>\r\n  <string>angle\t∠</string>\r\n  <string>overarc\t⌒</string>\r\n  <string" +
            ">equiv\t≡</string>\r\n  <string>sim\t∽</string>\r\n  <string>degree\t°</string>\r\n  <str" +
            "ing>sqrt\t√</string>\r\n  <string>parallel\t∥</string>\r\n  <string>forall\t∀</string>\r" +
            "\n  <string>exists\t∃</string>\r\n  <string>nexists\t∄</string>\r\n  <string>rightarrow" +
            "\t→</string>\r\n  <string>leftarrow\t←</string>\r\n  <string>leftrightarrow\t↔</string>" +
            "\r\n  <string>crightarrow\t⇒</string>\r\n  <string>cleftrightarrow\t⇔</string>\r\n  <str" +
            "ing>land\t∧</string>\r\n  <string>lnot\t¬</string>\r\n  <string>lor\t∨</string>\r\n  <str" +
            "ing>barwedge\t⊼</string>\r\n  <string>veebar\t⊻</string>\r\n  <string>oplus\t⊕</string>" +
            "\r\n  <string>otimes\t⊗</string>\r\n  <string>cdot\t⋅</string>\r\n  <string>nabla\t∇</str" +
            "ing>\r\n  <string>ldots\t…</string>\r\n  <string>ast\t∗</string>\r\n  <string>circ\t∘</st" +
            "ring>\r\n  <string>propto\t∝</string>\r\n  <string>mathbbn\tℕ</string>\r\n  <string>math" +
            "bbz\tℤ</string>\r\n  <string>mathbbq\tℚ</string>\r\n  <string>mathbbr\tℝ</string>\r\n  <s" +
            "tring>mathbbc\tℂ</string>\r\n  <string>dotcx\tẊ</string>\r\n  <string>ddotcx\tẌ</string" +
            ">\r\n  <string>dotx\tẋ</string>\r\n  <string>ddotx\tẍ</string>\r\n  <string>dotcy\tẎ</str" +
            "ing>\r\n  <string>ddotcy\tŸ</string>\r\n  <string>doty\tẏ</string>\r\n  <string>ddoty\tÿ<" +
            "/string>\r\n  <string>dotcz\tŻ</string>\r\n  <string>ddotcz\tZ̈</string>\r\n  <string>do" +
            "tz\tż</string>\r\n  <string>ddotz\tz̈</string>\r\n  <string>supa\tᵃ</string>\r\n  <string" +
            ">supb\tᵇ</string>\r\n  <string>supc\tᶜ</string>\r\n  <string>supd\tᵈ</string>\r\n  <strin" +
            "g>supe\tᵉ</string>\r\n  <string>supf\tᶠ</string>\r\n  <string>supg\tᵍ</string>\r\n  <stri" +
            "ng>suph\tʰ</string>\r\n  <string>supi\tⁱ</string>\r\n  <string>supj\tʲ</string>\r\n  <str" +
            "ing>supk\tᵏ</string>\r\n  <string>supl\tˡ</string>\r\n  <string>supm\tᵐ</string>\r\n  <st" +
            "ring>supn\tⁿ</string>\r\n  <string>supo\tᵒ</string>\r\n  <string>supp\tᵖ</string>\r\n  <s" +
            "tring>supr\tʳ</string>\r\n  <string>sups\tˢ</string>\r\n  <string>supt\tᵗ</string>\r\n  <" +
            "string>supu\tᵘ</string>\r\n  <string>supv\tᵛ</string>\r\n  <string>supw\tʷ</string>\r\n  " +
            "<string>supx\tˣ</string>\r\n  <string>supy\tʸ</string>\r\n  <string>supz\tᶻ</string>\r\n " +
            " <string>supca\tᴬ</string>\r\n  <string>supcb\tᴮ</string>\r\n  <string>supcc\tꟲ</string" +
            ">\r\n  <string>supcd\tᴰ</string>\r\n  <string>supce\tᴱ</string>\r\n  <string>supcf\tꟳ</st" +
            "ring>\r\n  <string>supcg\tᴳ</string>\r\n  <string>supch\tᴴ</string>\r\n  <string>supci\tᴵ" +
            "</string>\r\n  <string>supcj\tᴶ</string>\r\n  <string>supck\tᴷ</string>\r\n  <string>sup" +
            "cl\tᴸ</string>\r\n  <string>supcm\tᴹ</string>\r\n  <string>supcn\tᴺ</string>\r\n  <string" +
            ">supco\tᴼ</string>\r\n  <string>supcp\tᴾ</string>\r\n  <string>supcq\tꟴ</string>\r\n  <st" +
            "ring>supcr\tᴿ</string>\r\n  <string>supct\tᵀ</string>\r\n  <string>supcu\tᵁ</string>\r\n " +
            " <string>supcv\tⱽ</string>\r\n  <string>supcw\tᵂ</string>\r\n  <string>suba\tₐ</string>" +
            "\r\n  <string>sube\tₑ</string>\r\n  <string>subh\tₕ</string>\r\n  <string>subi\tᵢ</string" +
            ">\r\n  <string>subj\tⱼ</string>\r\n  <string>subk\tₖ</string>\r\n  <string>subl\tₗ</strin" +
            "g>\r\n  <string>subm\tₘ</string>\r\n  <string>subn\tₙ</string>\r\n  <string>subo\tₒ</stri" +
            "ng>\r\n  <string>subp\tₚ</string>\r\n  <string>subr\tᵣ</string>\r\n  <string>subs\tₛ</str" +
            "ing>\r\n  <string>subt\tₜ</string>\r\n  <string>subu\tᵤ</string>\r\n  <string>subv\tᵥ</st" +
            "ring>\r\n  <string>subx\tₓ</string>\r\n  <string>supalpha\tᵅ</string>\r\n  <string>supbe" +
            "ta\tᵝ</string>\r\n  <string>supgamma\tᵞ</string>\r\n  <string>supdelta\tᵟ</string>\r\n  <" +
            "string>supepsilon\tᵋ</string>\r\n  <string>suptheta\tᶿ</string>\r\n  <string>supiota\tᶥ" +
            "</string>\r\n  <string>supcphi\tᶲ</string>\r\n  <string>supphi\tᵠ</string>\r\n  <string>" +
            "supchi\tᵡ</string>\r\n  <string>subbeta\tᵦ</string>\r\n  <string>subgamma\tᵧ</string>\r\n" +
            "  <string>subrho\tᵨ</string>\r\n  <string>subphi\tᵩ</string>\r\n  <string>subchi\tᵪ</st" +
            "ring>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SymbolAliasList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SymbolAliasList"]));
            }
            set {
                this["SymbolAliasList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>IsPopup	True</string>
  <string>PopupSize	165</string>
  <string>PopupLocation	3</string>
  <string>PopupOpacity	0.5</string>
  <string>IsPopupColorBlack	True</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConfigKeyValueList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConfigKeyValueList"]));
            }
            set {
                this["ConfigKeyValueList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
